import { supabase, getSupabaseConfigError } from '../../lib/supabase';
import { MatchReminderMinutes, ThemePreference, UserPreferences, UserProfile } from '../../types';
const profileFromRow = (row: Record<string, unknown>): UserProfile => ({ id: String(row.id), name: typeof row.name === 'string' ? row.name : 'Aficionado', favoriteTeamId: typeof row.favorite_team_id === 'number' ? row.favorite_team_id : null, createdAt: String(row.created_at ?? ''), updatedAt: String(row.updated_at ?? '') });
const profileError = (message: string): Error => new Error(`Perfil: ${message}`);
export async function ensureProfile(userId: string, name: string): Promise<UserProfile> { if (!supabase) throw getSupabaseConfigError(); const normalizedName = name.trim() || 'Aficionado'; const { data, error } = await supabase.from('profiles').upsert({ id: userId, name: normalizedName }, { onConflict: 'id' }).select('*').single(); if (error || !data) throw profileError(error?.message || 'Supabase no devolvió el perfil creado.'); return profileFromRow(data as Record<string, unknown>); }
export async function getProfile(userId: string, fallbackName = 'Aficionado'): Promise<UserProfile | null> { if (!supabase) throw getSupabaseConfigError(); const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).maybeSingle(); if (error) throw profileError(error.message); if (data) return profileFromRow(data as Record<string, unknown>); return ensureProfile(userId, fallbackName); }
export async function updateFavoriteTeam(userId: string, teamId: number): Promise<void> { if (!supabase) throw getSupabaseConfigError(); const { error } = await supabase.from('profiles').update({ favorite_team_id: teamId }).eq('id', userId); if (error) throw profileError(error.message || 'No pudimos guardar el equipo favorito.'); }
function reminderMinutesValue(value: unknown): MatchReminderMinutes {
  return value === 15 || value === 30 || value === 60 ? value : 60;
}
export async function getPreferences(userId: string): Promise<UserPreferences | null> { if (!supabase) throw getSupabaseConfigError(); const { data, error } = await supabase.from('user_preferences').select('*').eq('user_id', userId).maybeSingle(); if (error) throw new Error('No pudimos cargar tus preferencias.'); if (!data) return null; const row = data as Record<string, unknown>; return { id: String(row.id), userId: String(row.user_id), theme: row.theme === 'light' || row.theme === 'dark' ? row.theme : 'system', notificationsEnabled: row.notifications_enabled !== false, matchStartNotifications: row.match_start_notifications !== false, matchResultNotifications: row.match_result_notifications !== false, matchReminderMinutes: reminderMinutesValue(row.match_reminder_minutes) }; }
export async function updatePreferences(userId: string, values: Partial<{ theme: ThemePreference; notificationsEnabled: boolean; matchStartNotifications: boolean; matchResultNotifications: boolean; matchReminderMinutes: MatchReminderMinutes }>): Promise<void> { if (!supabase) throw getSupabaseConfigError(); if (values.matchReminderMinutes !== undefined && ![15, 30, 60].includes(values.matchReminderMinutes)) throw new Error('El recordatorio debe ser de 15, 30 o 60 minutos.'); const payload = { ...(values.theme ? { theme: values.theme } : {}), ...(values.notificationsEnabled === undefined ? {} : { notifications_enabled: values.notificationsEnabled }), ...(values.matchStartNotifications === undefined ? {} : { match_start_notifications: values.matchStartNotifications }), ...(values.matchResultNotifications === undefined ? {} : { match_result_notifications: values.matchResultNotifications }), ...(values.matchReminderMinutes === undefined ? {} : { match_reminder_minutes: values.matchReminderMinutes }) }; const { error } = await supabase.from('user_preferences').update(payload).eq('user_id', userId); if (error) throw new Error('No pudimos guardar tus preferencias.'); }
