import { useQuery } from '@tanstack/react-query';
import { getStandings } from '../services/apiFootball/standingsService';
import { getNextFixture, getSportsDbEventDetail, getSportsDbEventLineup, getSportsDbEventStatistics, getSportsDbEventTimeline, getSportsDbFixtures } from '../services/sportsDb/sportsDbService';
import { getNews, NewsQuery } from '../services/news/newsService';
export const useStandings = () => useQuery({ queryKey: ['standings'], queryFn: getStandings });
export const useNextFixture = (team?: import('../types').Team | null) => useQuery({ queryKey: ['next-fixture', team?.id, team?.name], queryFn: () => getNextFixture(team as import('../types').Team), enabled: Boolean(team) });
export const useSportsDbFixtures = (enabled = true) => useQuery({ queryKey: ['sports-db-fixtures'], queryFn: getSportsDbFixtures, enabled });
export const useSportsDbEventDetail = (eventId?: string) => useQuery({ queryKey: ['sports-db-event-detail', eventId], queryFn: () => getSportsDbEventDetail(eventId as string), enabled: Boolean(eventId) });
export const useSportsDbEventTimeline = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-timeline', eventId], queryFn: () => getSportsDbEventTimeline(eventId as string), enabled: Boolean(eventId) && enabled });
export const useSportsDbEventStatistics = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-stats', eventId], queryFn: () => getSportsDbEventStatistics(eventId as string), enabled: Boolean(eventId) && enabled });
export const useSportsDbEventLineup = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-lineup', eventId], queryFn: () => getSportsDbEventLineup(eventId as string), enabled: Boolean(eventId) && enabled });
export const useNews = (request?: string | NewsQuery, enabled = true) => useQuery({ queryKey: ['news', request], queryFn: () => getNews(request), enabled, staleTime: 10 * 60 * 1000, retry: 0, retryOnMount: false });
