import { useQuery } from '@tanstack/react-query';
import { getFixture, getFixtures } from '../services/apiFootball/fixturesService';
import { getFixtureEvents } from '../services/apiFootball/eventsService';
import { getFixtureStatistics } from '../services/apiFootball/statisticsService';
import { getStandings } from '../services/apiFootball/standingsService';
import { getNextFixture, getSportsDbEventDetail, getSportsDbEventLineup, getSportsDbEventStatistics, getSportsDbEventTimeline, getSportsDbFixtures } from '../services/sportsDb/sportsDbService';
import { getTeam, getTeams } from '../services/apiFootball/teamsService';
import { getNews } from '../services/news/newsService';
export const useFixtures = (params?: { teamId?: number; status?: string }) => useQuery({ queryKey: ['fixtures', params], queryFn: () => getFixtures(params), enabled: params?.teamId !== 0 });
export const useFixture = (id: number) => useQuery({ queryKey: ['fixture', id], queryFn: () => getFixture(id), enabled: id > 0 });
export const useFixtureEvents = (id: number) => useQuery({ queryKey: ['fixture-events', id], queryFn: () => getFixtureEvents(id), enabled: id > 0 });
export const useFixtureStatistics = (id: number) => useQuery({ queryKey: ['fixture-statistics', id], queryFn: () => getFixtureStatistics(id), enabled: id > 0 });
export const useStandings = () => useQuery({ queryKey: ['standings'], queryFn: getStandings });
export const useNextFixture = (team?: import('../types').Team | null) => useQuery({ queryKey: ['next-fixture', team?.id, team?.name], queryFn: () => getNextFixture(team as import('../types').Team), enabled: Boolean(team) });
export const useSportsDbFixtures = () => useQuery({ queryKey: ['sports-db-fixtures'], queryFn: getSportsDbFixtures });
export const useSportsDbEventDetail = (eventId?: string) => useQuery({ queryKey: ['sports-db-event-detail', eventId], queryFn: () => getSportsDbEventDetail(eventId as string), enabled: Boolean(eventId) });
export const useSportsDbEventTimeline = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-timeline', eventId], queryFn: () => getSportsDbEventTimeline(eventId as string), enabled: Boolean(eventId) && enabled });
export const useSportsDbEventStatistics = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-stats', eventId], queryFn: () => getSportsDbEventStatistics(eventId as string), enabled: Boolean(eventId) && enabled });
export const useSportsDbEventLineup = (eventId?: string, enabled = true) => useQuery({ queryKey: ['sports-db-event-lineup', eventId], queryFn: () => getSportsDbEventLineup(eventId as string), enabled: Boolean(eventId) && enabled });
export const useTeams = () => useQuery({ queryKey: ['teams'], queryFn: getTeams });
export const useTeam = (id: number) => useQuery({ queryKey: ['team', id], queryFn: () => getTeam(id), enabled: id > 0 });
export const useNews = (query?: string) => useQuery({ queryKey: ['news', query], queryFn: () => getNews(query) });
