import { Fixture, FixtureEvent, MatchStatistic, MatchStatus, Standing, Team } from '../../types';
type RecordValue = Record<string, unknown>;
const record = (value: unknown): RecordValue => value !== null && typeof value === 'object' ? value as RecordValue : {};
const stringValue = (value: unknown): string | null => typeof value === 'string' && value.length > 0 ? value : null;
const numberValue = (value: unknown): number | null => typeof value === 'number' ? value : null;
export function mapTeam(raw: unknown): Team { const team = record(record(raw).team); const venue = record(record(raw).venue); return { id: numberValue(team.id) ?? 0, name: stringValue(team.name) ?? 'Equipo sin nombre', code: stringValue(team.code), logo: stringValue(team.logo), country: stringValue(team.country), founded: numberValue(team.founded), venue: stringValue(venue.name), city: stringValue(venue.city) }; }
const statusMap = (short: string): MatchStatus => ['NS', 'TBD'].includes(short) ? 'scheduled' : ['1H', 'HT', '2H', 'ET', 'BT', 'P', 'LIVE'].includes(short) ? 'live' : ['FT', 'AET', 'PEN'].includes(short) ? 'finished' : ['PST', 'CANC', 'ABD'].includes(short) ? 'postponed' : 'unknown';
export function mapFixture(raw: unknown): Fixture { const item = record(raw); const fixture = record(item.fixture); const teams = record(item.teams); const goals = record(item.goals); const status = record(fixture.status); const short = stringValue(status.short) ?? '—'; return { id: numberValue(fixture.id) ?? 0, date: stringValue(fixture.date) ?? '', timestamp: numberValue(fixture.timestamp), status: statusMap(short), statusShort: short, elapsed: numberValue(status.elapsed), venue: stringValue(record(fixture.venue).name), homeTeam: mapTeam({ team: record(teams.home) }), awayTeam: mapTeam({ team: record(teams.away) }), homeGoals: numberValue(goals.home), awayGoals: numberValue(goals.away), round: stringValue(record(fixture.league).round) }; }
export function mapEvent(raw: unknown): FixtureEvent { const item = record(raw); const time = record(item.time); const player = record(item.player); const assist = record(item.assist); const team = record(item.team); const type = stringValue(item.type); const detail = stringValue(item.detail); const eventType: FixtureEvent['type'] = type === 'Goal' ? 'goal' : type === 'Card' && detail?.toLowerCase().includes('red') ? 'red_card' : type === 'Card' ? 'yellow_card' : type === 'subst' ? 'substitution' : type === 'Var' ? 'var' : 'unknown'; return { time: numberValue(time.elapsed), type: eventType, detail, player: stringValue(player.name), assist: stringValue(assist.name), teamId: numberValue(team.id) }; }
export function mapStatistics(raw: unknown): MatchStatistic[] { const item = record(raw); const stats = Array.isArray(item.statistics) ? item.statistics : []; const first = record(stats[0]); const second = record(stats[1]); const left = Array.isArray(first.statistics) ? first.statistics : []; const right = Array.isArray(second.statistics) ? second.statistics : []; const rightMap = new Map<string, string | number | null>(); for (const entry of right) { const row = record(entry); const type = stringValue(row.type); if (type) rightMap.set(type, typeof row.value === 'number' || typeof row.value === 'string' ? row.value : null); } return left.flatMap((entry) => { const row = record(entry); const label = stringValue(row.type); if (!label) return []; const home = typeof row.value === 'number' || typeof row.value === 'string' ? row.value : null; return [{ label, home, away: rightMap.get(label) ?? null }]; }); }
export function mapStanding(raw: unknown): Standing { const item = record(raw); const team = mapTeam({ team: record(item.team) }); const all = record(item.all); const goals = record(item.goals); return { rank: numberValue(item.rank) ?? 0, team, played: numberValue(all.played) ?? 0, wins: numberValue(all.win) ?? 0, draws: numberValue(all.draw) ?? 0, losses: numberValue(all.lose) ?? 0, goalsFor: numberValue(goals.for) ?? 0, goalsAgainst: numberValue(goals.against) ?? 0, goalDifference: numberValue(item.goalsDiff) ?? 0, points: numberValue(item.points) ?? 0, form: stringValue(item.form) }; }
