import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, View } from 'react-native';
import { AppText, MatchCard, Screen, StateView } from '../../components/ui';
import { useSportsDbFixtures } from '../../src/hooks/useData';
import { useTheme } from '../../src/theme/ThemeProvider';
type Filter = 'all' | 'live' | 'scheduled' | 'finished';
export default function MatchesScreen(): React.JSX.Element { const { colors } = useTheme(); const [filter, setFilter] = useState<Filter>('all'); const query = useSportsDbFixtures(); const fixtures = useMemo(() => sortFixtures(query.data ?? [], filter), [filter, query.data]); return <Screen refreshing={query.isRefetching} onRefresh={() => void query.refetch()}><AppText size={12} color={colors.primary} weight="bold">MY LIGA MX · JORNADA</AppText><AppText size={30} weight="bold">Partidos</AppText><AppText color={colors.muted}>Liga MX · temporada configurada</AppText><View style={{ flexDirection: 'row', gap: 6, marginVertical: 20, padding: 5, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }}>{(['all', 'live', 'scheduled', 'finished'] as Filter[]).map((value) => <FilterChip key={value} value={value} active={filter === value} onPress={() => setFilter(value)} />)}</View>{query.isLoading ? <StateView kind="loading" /> : query.isError ? <StateView kind="error" message={query.error instanceof Error ? query.error.message : undefined} onRetry={() => void query.refetch()} /> : fixtures.length ? fixtures.map((fixture) => <MatchCard key={fixture.id} fixture={fixture} onPress={() => { const eventId = fixture.idEvent ?? String(fixture.id); console.log('MATCH PRESS:', { id: fixture.id, rawIdEvent: fixture.idEvent, home: fixture.homeTeam, away: fixture.awayTeam }); router.push({ pathname: '/match/[id]', params: { id: eventId } }); }} />) : <StateView kind="empty" message="No hay partidos disponibles para este filtro." />}</Screen>; }
function sortFixtures(fixtures: NonNullable<ReturnType<typeof useSportsDbFixtures>['data']>, filter: Filter) { const filtered = filter === 'all' ? fixtures : fixtures.filter((fixture) => fixture.status === filter); return [...filtered].sort((left, right) => { const leftTime = left.timestamp ?? 0; const rightTime = right.timestamp ?? 0; if (filter === 'finished') return rightTime - leftTime; return leftTime - rightTime; }); }
function FilterChip({ value, active, onPress }: { value: Filter; active: boolean; onPress: () => void }): React.JSX.Element { const { colors } = useTheme(); const labels: Record<Filter, string> = { all: 'Todos', live: 'En vivo', scheduled: 'Próximos', finished: 'Finalizados' }; return <Pressable onPress={onPress} style={{ paddingHorizontal: 13, paddingVertical: 9, borderRadius: 20, backgroundColor: active ? colors.primary : colors.surface, borderWidth: 1, borderColor: active ? colors.primary : colors.border }}><AppText size={12} weight="bold" color={active ? '#FFF' : colors.muted}>{labels[value]}</AppText></Pressable>; }
