import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, View } from 'react-native';
import { AppText, NewsCard, Screen, StateView } from '../../components/ui';
import { useAuth } from '../../src/context/AuthProvider';
import { useNews, useTeam } from '../../src/hooks/useData';
import { useTheme } from '../../src/theme/ThemeProvider';
export default function NewsScreen(): React.JSX.Element { const { colors } = useTheme(); const { profile } = useAuth(); const teamQuery = useTeam(profile?.favoriteTeamId ?? 0); const [onlyTeam, setOnlyTeam] = useState(false); const query = useNews(onlyTeam && teamQuery.data ? `${teamQuery.data.name} Liga MX` : undefined); const articles = useMemo(() => query.data ?? [], [query.data]); return <Screen refreshing={query.isRefetching} onRefresh={() => void query.refetch()}><AppText size={30} weight="bold">Noticias</AppText><AppText color={colors.muted}>Actualidad de Liga MX y tu equipo.</AppText><View style={{ flexDirection: 'row', gap: 10, marginVertical: 18 }}><Chip text="Todas" active={!onlyTeam} onPress={() => setOnlyTeam(false)} /><Chip text="Mi equipo" active={onlyTeam} onPress={() => setOnlyTeam(true)} /></View>{query.isLoading ? <StateView kind="loading" /> : query.isError ? <StateView kind="error" message={query.error instanceof Error ? query.error.message : undefined} onRetry={() => void query.refetch()} /> : !articles.length ? <StateView kind="empty" message="No hay noticias disponibles." /> : articles.map((article) => <NewsCard key={article.id} article={article} onPress={() => router.push(`/news/${encodeURIComponent(article.id)}`)} />)}</Screen>; }
function Chip({ text, active, onPress }: { text: string; active: boolean; onPress: () => void }): React.JSX.Element { const { colors } = useTheme(); return <Pressable onPress={onPress} style={{ paddingHorizontal: 16, paddingVertical: 9, borderRadius: 20, backgroundColor: active ? colors.primary : colors.surface, borderWidth: 1, borderColor: active ? colors.primary : colors.border }}><AppText size={13} weight="bold" color={active ? '#FFF' : colors.muted}>{text}</AppText></Pressable>; }
